# Generated by Django 3.2 on 2022-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_education',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='최종학력'),
        ),
    ]
