# Generated by Django 3.2 on 2022-05-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='v_task',
            field=models.CharField(default='', max_length=256, verbose_name='시각화_Task'),
        ),
    ]
