# Generated by Django 3.2 on 2022-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='v_task',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='시각화_Task'),
        ),
    ]
