# Generated by Django 3.2 on 2021-10-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='set_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='chart',
        ),
        migrations.AddField(
            model_name='user',
            name='purpose',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='목적'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='연령대'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_education',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='최종학력'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_major',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='전공'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='choice_id'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='quiz_id',
            field=models.SmallIntegerField(verbose_name='quiz_id'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(max_length=256, verbose_name='사용자'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='result_id'),
        ),
    ]
