# Generated by Django 3.2 on 2021-06-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_quiz_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='quiz_id',
            field=models.SmallIntegerField(verbose_name='quiz_id'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(max_length=256, verbose_name='사용자'),
        ),
    ]
