# Generated by Django 3.2 on 2022-05-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_v_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='v_task',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='시각화_Task'),
        ),
    ]
