# Generated by Django 3.2 on 2021-06-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20210622_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='choice_id'),
        ),
    ]
