# Generated by Django 3.2 on 2022-05-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_v_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='v_task',
            field=models.CharField(default='', max_length=256, null=True, verbose_name='시각화Task'),
        ),
    ]
