# Generated by Django 3.2 on 2022-05-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_v_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='v_task',
        ),
    ]
