# Generated by Django 3.2 on 2021-06-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_answer_choice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='set_id',
        ),
    ]
