# Generated by Django 3.2 on 2021-10-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_alter_result_result_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='purpose',
            field=models.CharField(default=None, max_length=256, verbose_name='목적'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_age',
            field=models.CharField(default=None, max_length=256, verbose_name='연령대'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_education',
            field=models.CharField(default=None, max_length=256, verbose_name='최종학력'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_major',
            field=models.CharField(default=None, max_length=256, verbose_name='전공'),
        ),
    ]
